# Generated by Django 6.0.6 on 2026-07-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0009_alter_bulksyncjob_creado_alter_pincodeusado_creado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('definicion', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte guardado',
                'verbose_name_plural': 'reportes guardados',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nombre'), name='reporte_guardado_unico_por_usuario')],
            },
        ),
    ]
