# Generated by Django 6.0.6 on 2026-07-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0010_reporteguardado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteguardado',
            name='compartido',
            field=models.BooleanField(default=False, verbose_name='Compartido con todos'),
        ),
    ]
