# Generated by Django 6.0.6 on 2026-08-11 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0011_reporteguardado_compartido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioTelevisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, default='', max_length=50, verbose_name='Dirección MAC')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Número de serie')),
                ('numero_credito', models.CharField(blank=True, default='', max_length=60, verbose_name='Número de crédito')),
                ('campo', models.CharField(choices=[('mac_address', 'Dirección MAC'), ('serial_number', 'Número de serie'), ('numero_credito', 'Número de crédito')], max_length=20, verbose_name='Campo')),
                ('valor_anterior', models.CharField(blank=True, default='', max_length=120, verbose_name='Valor anterior')),
                ('valor_nuevo', models.CharField(blank=True, default='', max_length=120, verbose_name='Valor nuevo')),
                ('origen', models.CharField(choices=[('individual', 'Individual'), ('masivo', 'Masivo')], default='individual', max_length=12, verbose_name='Origen')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('televisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios', to='televisores.televisor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_televisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de televisor',
                'verbose_name_plural': 'historial de cambios',
                'ordering': ['-creado', '-id'],
                'indexes': [models.Index(fields=['serial_number'], name='televisores_serial__a52d9e_idx'), models.Index(fields=['mac_address'], name='televisores_mac_add_ea3557_idx')],
            },
        ),
    ]
