# Generated by Django 6.0.6 on 2026-09-03 21:44

import televisores.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0012_cambiotelevisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, validators=[televisores.validadores.validar_serial], verbose_name='Número de serie'),
        ),
    ]
