# Generated by Django 6.0.6 on 2026-07-15 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Para identificar al integrador, p. ej. "ERP de Google".', max_length=100, verbose_name='nombre')),
                ('prefijo', models.CharField(editable=False, max_length=16, unique=True, verbose_name='prefijo')),
                ('hash_clave', models.CharField(editable=False, max_length=64, verbose_name='hash')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('ips_permitidas', models.TextField(blank=True, default='', help_text='IPs o rangos CIDR (uno por línea). Vacío = cualquier IP.', verbose_name='IPs permitidas')),
                ('expira', models.DateTimeField(blank=True, null=True, verbose_name='expira el')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-creada'],
            },
        ),
    ]
