# Generated by Django 6.0.6 on 2026-08-11 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_accent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='hash del token')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('expira_en', models.DateTimeField(verbose_name='expira en')),
                ('usado_en', models.DateTimeField(blank=True, null=True, verbose_name='usado en')),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de la solicitud')),
                ('ip_uso', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'token de recuperación',
                'verbose_name_plural': 'tokens de recuperación',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['user', '-creado'], name='users_passw_user_id_3e7fcd_idx')],
            },
        ),
    ]
