# Generated by Django 6.0.6 on 2026-08-11 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='iniciada')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='última actividad')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='navegador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_activa', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'sesión activa',
                'verbose_name_plural': 'sesiones activas',
                'ordering': ['-ultima_actividad'],
            },
        ),
    ]
