# Generated by Django 6.0.6 on 2026-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sesionactiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionactiva',
            name='navegador_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='id de navegador'),
        ),
        migrations.AddConstraint(
            model_name='sesionactiva',
            constraint=models.UniqueConstraint(condition=models.Q(('navegador_id', ''), _negated=True), fields=('navegador_id',), name='sesion_unica_por_navegador'),
        ),
    ]
